# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.4.4"
stylua = "johnnymorganz/stylua@2.0.2"
wally = "upliftGames/wally@0.3.2"
rbxcloud = "Sleitnick/rbxcloud@0.15.1"
lune = "lune-org/lune@0.8.9"
selene = "Kampfkarren/selene@0.28.0"
