# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.4.4"
stylua = "johnnymorganz/stylua@0.20.0"
wally = "upliftGames/wally@0.3.2"
rbxcloud = "Sleitnick/rbxcloud@0.14.0"
