name: continuous integration

on:
  push:
    branches: master
    paths: src/**/*.luau

jobs:
  publish:
    env:
      NO_REPLY_EMAIL: 148505724+magicchex@users.noreply.github.com
      USERNAME: magicchex
      REPOSITORY: roblox-template
      SOURCE_FOLDER: src
      UNIVERSE_ID: 6501573027
      PLACE_ID: 75130637870501
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Node
        uses: actions/setup-node@v4
        
      - name: Install Cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
        
      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        
      - name: Install Git
        run: sudo apt-get install git
        
      - name: Setup Git
        run: |
          git config --global user.email $NO_REPLY_EMAIL
          git config --global user.name $USERNAME
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$USERNAME/$REPOSITORY.git
        
      - name: Install Aftman tools
        run: aftman install
        
      - name: Install Moonwave
        run: npx moonwave

      - name: Install Wally Dependencies
        run: |
          if [ -f "wally.toml" ]; then
            wally install
          else
            echo "Skipped Wally."
          fi
      - name: Build and Upload Place to Roblox
        run: rojo upload --asset_id $PLACE_ID --universe_id $UNIVERSE_ID --api_key ${{ secrets.PLACE_PUBLISHING_KEY }}
        
      - name: Build Documentation
        run: moonwave build --publish --code $SOURCE_FOLDER