name: format

on:
  pull_request:
    branches:
      - master
    paths: src/**.luau

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: rust_cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: aftman_setup
        uses: ok-nick/setup-aftman@v0.4.2
      - name: install aftman
        run: aftman install
      - name: install selene
        run: cargo install selene
      - name: run selene
        run: selene src
      - name: run stylua
        run: stylua --indent-type Tabs --quote-style ForceSingle  --collapse-simple-statement Never --call-parentheses Always src


