name: format on pull request

on:
  pull_request:
    branches:
      - master
    paths: src/**/*.luau

env:
  GIT_NO_REPLY_EMAIL: actions@github.com
  GIT_USERNAME: GitHub Actions
  REPOSITORY_OWNER: magicchex
  REPOSITORY_NAME: roblox-template
  SOURCE_FOLDER: src
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  run-selene-linter:
    needs: checkout
    runs-on: ubuntu-22.04
    steps:
      - name: Install Cargo
        run: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Selene
        run: cargo install selene
      - name: Selene
        run: selene $SOURCE_FOLDER
  run-stylua-formatter:
    needs: run-selene-linter
    runs-on: ubuntu-22.04
    steps:
      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2
      
      - name: Install Aftman Tools
        run: aftman install
      
      - name: Stylua
        run: stylua --indent-type Tabs --quote-style ForceSingle --collapse-simple-statement Never --call-parentheses Always $SOURCE_FOLDER

      - name: Check for changes
        id: git-change
        run: echo "::set-output name=change::$(git diff)"
      
      - name: Commit changes made by Stylua
        if: steps.git-change.outputs.change != ''
        run: |
          git config --global user.name $GIT_USERNAME
          git config --global user.email $GIT_NO_REPLY_EMAIL
          git add .
          git commit -m "Apply code formatting"
          git push